package com.bs.glr.bean;

import java.util.Date;

public class BsBorrow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.uid
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.uname
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.goods_id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.goods_name
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.boorrw_status
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private String boorrwStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.address
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.cnum
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private Integer cnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.op_er
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private String opEr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.ctimm
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    private Date ctimm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.id
     *
     * @return the value of bs_borrow.id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.id
     *
     * @param id the value for bs_borrow.id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.uid
     *
     * @return the value of bs_borrow.uid
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.uid
     *
     * @param uid the value for bs_borrow.uid
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.uname
     *
     * @return the value of bs_borrow.uname
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.uname
     *
     * @param uname the value for bs_borrow.uname
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.goods_id
     *
     * @return the value of bs_borrow.goods_id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.goods_id
     *
     * @param goodsId the value for bs_borrow.goods_id
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.goods_name
     *
     * @return the value of bs_borrow.goods_name
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.goods_name
     *
     * @param goodsName the value for bs_borrow.goods_name
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.boorrw_status
     *
     * @return the value of bs_borrow.boorrw_status
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public String getBoorrwStatus() {
        return boorrwStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.boorrw_status
     *
     * @param boorrwStatus the value for bs_borrow.boorrw_status
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setBoorrwStatus(String boorrwStatus) {
        this.boorrwStatus = boorrwStatus == null ? null : boorrwStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.address
     *
     * @return the value of bs_borrow.address
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.address
     *
     * @param address the value for bs_borrow.address
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.cnum
     *
     * @return the value of bs_borrow.cnum
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public Integer getCnum() {
        return cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.cnum
     *
     * @param cnum the value for bs_borrow.cnum
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setCnum(Integer cnum) {
        this.cnum = cnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.op_er
     *
     * @return the value of bs_borrow.op_er
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public String getOpEr() {
        return opEr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.op_er
     *
     * @param opEr the value for bs_borrow.op_er
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setOpEr(String opEr) {
        this.opEr = opEr == null ? null : opEr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.ctimm
     *
     * @return the value of bs_borrow.ctimm
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public Date getCtimm() {
        return ctimm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.ctimm
     *
     * @param ctimm the value for bs_borrow.ctimm
     *
     * @mbg.generated Thu Mar 14 09:50:23 CST 2024
     */
    public void setCtimm(Date ctimm) {
        this.ctimm = ctimm;
    }
}