package com.bs.glr.bean;

public class BsDataCk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_data_ck.id
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_data_ck.wd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    private String wd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_data_ck.sd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    private String sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_data_ck.yw
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    private String yw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_data_ck.id
     *
     * @return the value of bs_data_ck.id
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_data_ck.id
     *
     * @param id the value for bs_data_ck.id
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_data_ck.wd
     *
     * @return the value of bs_data_ck.wd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public String getWd() {
        return wd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_data_ck.wd
     *
     * @param wd the value for bs_data_ck.wd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public void setWd(String wd) {
        this.wd = wd == null ? null : wd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_data_ck.sd
     *
     * @return the value of bs_data_ck.sd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public String getSd() {
        return sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_data_ck.sd
     *
     * @param sd the value for bs_data_ck.sd
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public void setSd(String sd) {
        this.sd = sd == null ? null : sd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_data_ck.yw
     *
     * @return the value of bs_data_ck.yw
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public String getYw() {
        return yw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_data_ck.yw
     *
     * @param yw the value for bs_data_ck.yw
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    public void setYw(String yw) {
        this.yw = yw == null ? null : yw.trim();
    }
}