package com.bs.glr.bean;

public class BsGoodsSort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_goods_sort.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_goods_sort.sort_name
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    private String sortName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_goods_sort.id
     *
     * @return the value of bs_goods_sort.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_goods_sort.id
     *
     * @param id the value for bs_goods_sort.id
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_goods_sort.sort_name
     *
     * @return the value of bs_goods_sort.sort_name
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_goods_sort.sort_name
     *
     * @param sortName the value for bs_goods_sort.sort_name
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }
}