package com.bs.glr.bean;

import lombok.Data;

@Data
public class BsUser {

    Integer score;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.id
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.uname
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.pwd
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.identity
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.age
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.sex
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.major
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.grade
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.email
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user.goods_count
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    private Integer goodsCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.id
     *
     * @return the value of bs_user.id
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.id
     *
     * @param id the value for bs_user.id
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.uname
     *
     * @return the value of bs_user.uname
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.uname
     *
     * @param uname the value for bs_user.uname
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.pwd
     *
     * @return the value of bs_user.pwd
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.pwd
     *
     * @param pwd the value for bs_user.pwd
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.identity
     *
     * @return the value of bs_user.identity
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.identity
     *
     * @param identity the value for bs_user.identity
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.age
     *
     * @return the value of bs_user.age
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.age
     *
     * @param age the value for bs_user.age
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.sex
     *
     * @return the value of bs_user.sex
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.sex
     *
     * @param sex the value for bs_user.sex
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.major
     *
     * @return the value of bs_user.major
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.major
     *
     * @param major the value for bs_user.major
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.grade
     *
     * @return the value of bs_user.grade
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.grade
     *
     * @param grade the value for bs_user.grade
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.email
     *
     * @return the value of bs_user.email
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.email
     *
     * @param email the value for bs_user.email
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user.goods_count
     *
     * @return the value of bs_user.goods_count
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user.goods_count
     *
     * @param goodsCount the value for bs_user.goods_count
     *
     * @mbg.generated Fri Apr 29 23:53:19 CST 9999
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }
}