package com.bs.glr.mapper;

import com.bs.glr.bean.BsDataCk;
import com.bs.glr.bean.BsDataCkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsDataCkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    long countByExample(BsDataCkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int deleteByExample(BsDataCkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int insert(BsDataCk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int insertSelective(BsDataCk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    List<BsDataCk> selectByExample(BsDataCkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    BsDataCk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") BsDataCk record, @Param("example") BsDataCkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int updateByExample(@Param("record") BsDataCk record, @Param("example") BsDataCkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int updateByPrimaryKeySelective(BsDataCk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_data_ck
     *
     * @mbg.generated Sun Jul 16 17:21:02 CST 2023
     */
    int updateByPrimaryKey(BsDataCk record);
}