package com.bs.glr.mapper;

import com.bs.glr.bean.BsGoodsAddress;
import com.bs.glr.bean.BsGoodsAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsGoodsAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    long countByExample(BsGoodsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int deleteByExample(BsGoodsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int insert(BsGoodsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int insertSelective(BsGoodsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    List<BsGoodsAddress> selectByExample(BsGoodsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    BsGoodsAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByExampleSelective(@Param("record") BsGoodsAddress record, @Param("example") BsGoodsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByExample(@Param("record") BsGoodsAddress record, @Param("example") BsGoodsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByPrimaryKeySelective(BsGoodsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_address
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByPrimaryKey(BsGoodsAddress record);
}