package com.bs.glr.mapper;

import com.bs.glr.bean.BsGoodsSort;
import com.bs.glr.bean.BsGoodsSortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsGoodsSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    long countByExample(BsGoodsSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int deleteByExample(BsGoodsSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int insert(BsGoodsSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int insertSelective(BsGoodsSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    List<BsGoodsSort> selectByExample(BsGoodsSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    BsGoodsSort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByExampleSelective(@Param("record") BsGoodsSort record, @Param("example") BsGoodsSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByExample(@Param("record") BsGoodsSort record, @Param("example") BsGoodsSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByPrimaryKeySelective(BsGoodsSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_goods_sort
     *
     * @mbg.generated Sun Feb 27 21:36:07 CST 9999
     */
    int updateByPrimaryKey(BsGoodsSort record);
}